/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;

import control.AdmDatos;
import control.CitaJpaController;
import control.TutorJpaController;
import control.TutoradoJpaController;
import control.TutoriaJpaController;
import modelo.Cita;
import modelo.DatosTablaCitas;
import modelo.MTablaCita;
import modelo.MTtutor;
import modelo.Tutor;
import modelo.Tutorado;
import modelo.Tutoria;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Hp EliteBook
 */
public class IMenuTutorias extends javax.swing.JFrame {
private Tutor tutor;
private TutorJpaController cTutor;
private List<Tutor> tutores;
private Tutorado tutorado;
private TutoradoJpaController cTutorado;
private List<Tutorado> tutorados;
private MTtutor mtt;
private DefaultListModel mestudiantes, mtutorados;
private Map<String,Tutorado> tutorado_nom = new HashMap<>();
private final String SELECCIONA = "Selecciona Tutor";
private final String SELECCIONADO  = "Tutor Seleccionado";
private String[] Carreras = {"Sistemas","Civil","Administracion", "Electronica"};
private SpinnerNumberModel snm;
private int max = 50; //Regla del negocioy
private int min = 0;
private Cita cita;
private List<Cita> citas;
private AdmDatos adm;
private List<Tutorado> tutorados_s;
private Map<String,Tutor> tutor_nom = new HashMap<>();
private Map<Integer,Cita> cita_horas = new HashMap<>();
private MTablaCita modTabCita;
private ArrayList<DatosTablaCitas> datosCitas;
private CitaJpaController cCita;
private Tutoria tutoria;
private TutoriaJpaController cTutoria;
private List<Tutoria> tutorias;
private Date fecha;
private ImageIcon iconMiniatura;

    /**
     * Creates new form IMenuTutorias
     */
    public IMenuTutorias() {
        initComponents();
        adm = new AdmDatos();
        cTutor = new TutorJpaController(AdmDatos.getEnf());
        tutores = cTutor.findTutorEntities();
        cTutorado = new TutoradoJpaController(AdmDatos.getEnf());
        tutorados = cTutorado.findTutoradoEntities();
        cCita = new CitaJpaController(AdmDatos.getEnf());
        citas = cCita.findCitaEntities();
        cTutoria =  new TutoriaJpaController(AdmDatos.getEnf());
        // Inicializacion de Agregar Tutor
        mtt = new MTtutor(tutores);
        ttutores.setModel(mtt);
        configurarComboBox();
        configurarJSpinner();
        // Inicializacion de Crear Tutoria
        FechaActual.setText("Fecha: " + getFecha());
        cargarTutoresCita();   
        //Inicializacion de Asignar Tutor
        cargarTutores();
        cargarEstudiantes();
        estudiantes.setModel(mestudiantes);
        estudiantes.setSelectionMode(1);
        tutoradoss.setModel(mtutorados);
        iconMiniatura = redimensionarImagen("imagenes/icono.png", 350, 500); // NUEVA LÍNEA (relativa al paquete 'vista')
        ImagenTutor.setIcon(iconMiniatura);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JTabbedPane();
        PTutorados = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PTutores = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        PInicio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttutores = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ttutores1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ttutores2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        ttutores3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        AgregarTutor = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ddh = new javax.swing.JTextField();
        dnt = new javax.swing.JSpinner();
        cbCarreras = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        ImagenTutor = new javax.swing.JLabel();
        AsignarTutor = new javax.swing.JPanel();
        moverTut = new javax.swing.JButton();
        asignarTutorado = new javax.swing.JButton();
        aceptarTutor = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        bct = new javax.swing.JButton();
        LTutores = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        estudiantes = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tutoradoss = new javax.swing.JList<>();
        moverEst = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        PCitas = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        PTutorias = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        RegistroTutoria = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ltutorados = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        ListaTutor = new javax.swing.JComboBox<>();
        Aceptar = new javax.swing.JButton();
        FechaActual = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(102, 0, 0));
        Menu.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        Menu.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N

        jPanel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel12.setText("Buscar Citas");

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setText("Ingrese No Control");

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Buscar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(44, 44, 44)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addComponent(jButton2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel21))
                .addGap(113, 113, 113)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("VerCitas", jPanel4);

        javax.swing.GroupLayout PTutoradosLayout = new javax.swing.GroupLayout(PTutorados);
        PTutorados.setLayout(PTutoradosLayout);
        PTutoradosLayout.setHorizontalGroup(
            PTutoradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTutoradosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        PTutoradosLayout.setVerticalGroup(
            PTutoradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        Menu.addTab("Tutorado", PTutorados);

        jTabbedPane2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        ttutores.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ttutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(ttutores);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Control de Registrados");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Instituto Tecnológico de Oaxaca");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Tutores Registrados");

        ttutores1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ttutores1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane5.setViewportView(ttutores1);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Estudiantes Registrados");

        ttutores2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ttutores2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane6.setViewportView(ttutores2);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Citas Creadas");

        ttutores3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ttutores3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane7.setViewportView(ttutores3);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Tutorias Creadas");

        javax.swing.GroupLayout PInicioLayout = new javax.swing.GroupLayout(PInicio);
        PInicio.setLayout(PInicioLayout);
        PInicioLayout.setHorizontalGroup(
            PInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PInicioLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(157, 157, 157))
            .addGroup(PInicioLayout.createSequentialGroup()
                .addGroup(PInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PInicioLayout.createSequentialGroup()
                        .addGap(747, 747, 747)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PInicioLayout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PInicioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PInicioLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PInicioLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(190, 190, 190))
            .addGroup(PInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PInicioLayout.createSequentialGroup()
                    .addGap(198, 198, 198)
                    .addComponent(jLabel11)
                    .addContainerGap(703, Short.MAX_VALUE)))
        );
        PInicioLayout.setVerticalGroup(
            PInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PInicioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addGroup(PInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(PInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(48, 48, 48)
                .addGroup(PInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PInicioLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(PInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PInicioLayout.createSequentialGroup()
                    .addContainerGap(439, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(226, 226, 226)))
        );

        jTabbedPane2.addTab("Control", PInicio);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("No Targeta:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Nombre:");

        dn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Carrera");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Dias/Horas:");

        ddh.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ddh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddhActionPerformed(evt);
            }
        });

        dnt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        cbCarreras.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cbCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCarrerasActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Agregar Registro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel15.setText("Tutores");

        javax.swing.GroupLayout AgregarTutorLayout = new javax.swing.GroupLayout(AgregarTutor);
        AgregarTutor.setLayout(AgregarTutorLayout);
        AgregarTutorLayout.setHorizontalGroup(
            AgregarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarTutorLayout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AgregarTutorLayout.createSequentialGroup()
                .addGroup(AgregarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarTutorLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(AgregarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(AgregarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddh, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dn, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dnt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AgregarTutorLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImagenTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        AgregarTutorLayout.setVerticalGroup(
            AgregarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarTutorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(AgregarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarTutorLayout.createSequentialGroup()
                        .addGroup(AgregarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(dnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(AgregarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(dn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(AgregarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ddh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(AgregarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(89, 89, 89)
                        .addComponent(jButton1))
                    .addComponent(ImagenTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Agregar Tutor", AgregarTutor);

        moverTut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        moverTut.setText("< Mover Estudiante");
        moverTut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moverTutActionPerformed(evt);
            }
        });

        asignarTutorado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        asignarTutorado.setText("Asignar Tutorado");
        asignarTutorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarTutoradoActionPerformed(evt);
            }
        });

        aceptarTutor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        aceptarTutor.setText("Aceptar Tutor");
        aceptarTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarTutorActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setText("Estudiantes Disponibles");

        bct.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bct.setText("Cambiar Tutor");
        bct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bctActionPerformed(evt);
            }
        });

        LTutores.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LTutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setText("Selecciona Tutor:");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setText("Estudiantes Asignados");

        estudiantes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        estudiantes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(estudiantes);

        tutoradoss.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tutoradoss.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(tutoradoss);

        moverEst.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        moverEst.setText("Mover Estudiante >");
        moverEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moverEstActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Asignar Tutor");

        javax.swing.GroupLayout AsignarTutorLayout = new javax.swing.GroupLayout(AsignarTutor);
        AsignarTutor.setLayout(AsignarTutorLayout);
        AsignarTutorLayout.setHorizontalGroup(
            AsignarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AsignarTutorLayout.createSequentialGroup()
                .addGroup(AsignarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AsignarTutorLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(AsignarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AsignarTutorLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LTutores, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AsignarTutorLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addGroup(AsignarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(moverTut)
                                    .addComponent(moverEst)
                                    .addGroup(AsignarTutorLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(asignarTutorado)))
                                .addGap(14, 14, 14)))
                        .addGap(18, 18, 18)
                        .addGroup(AsignarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AsignarTutorLayout.createSequentialGroup()
                                .addComponent(aceptarTutor)
                                .addGap(35, 35, 35)
                                .addComponent(bct))
                            .addGroup(AsignarTutorLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AsignarTutorLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AsignarTutorLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(145, 145, 145))
        );
        AsignarTutorLayout.setVerticalGroup(
            AsignarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AsignarTutorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel19)
                .addGap(61, 61, 61)
                .addGroup(AsignarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptarTutor)
                    .addComponent(bct)
                    .addComponent(jLabel17))
                .addGap(98, 98, 98)
                .addGroup(AsignarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addGap(31, 31, 31)
                .addGroup(AsignarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AsignarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AsignarTutorLayout.createSequentialGroup()
                            .addComponent(moverTut)
                            .addGap(38, 38, 38)
                            .addComponent(moverEst)
                            .addGap(57, 57, 57))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(asignarTutorado)
                .addGap(60, 60, 60))
        );

        jTabbedPane2.addTab("Asignar Tutor", AsignarTutor);

        javax.swing.GroupLayout PTutoresLayout = new javax.swing.GroupLayout(PTutores);
        PTutores.setLayout(PTutoresLayout);
        PTutoresLayout.setHorizontalGroup(
            PTutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        PTutoresLayout.setVerticalGroup(
            PTutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        Menu.addTab("Administrador", PTutores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Crear Cita", jPanel1);

        javax.swing.GroupLayout PCitasLayout = new javax.swing.GroupLayout(PCitas);
        PCitas.setLayout(PCitasLayout);
        PCitasLayout.setHorizontalGroup(
            PCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        PCitasLayout.setVerticalGroup(
            PCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        Menu.addTab("Cita", PCitas);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("Registro de Asistencia");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel14.setText("Registro de Tutoria");

        RegistroTutoria.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        RegistroTutoria.setText("Registrar Tutoria");

        ltutorados.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ltutorados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(ltutorados);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel20.setText("Tutor");

        ListaTutor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ListaTutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListaTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaTutorActionPerformed(evt);
            }
        });

        Aceptar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        FechaActual.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FechaActual.setText("Fecha: ");

        javax.swing.GroupLayout PTutoriasLayout = new javax.swing.GroupLayout(PTutorias);
        PTutorias.setLayout(PTutoriasLayout);
        PTutoriasLayout.setHorizontalGroup(
            PTutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTutoriasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PTutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTutoriasLayout.createSequentialGroup()
                        .addComponent(RegistroTutoria)
                        .addGap(432, 432, 432))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTutoriasLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(422, 422, 422))))
            .addGroup(PTutoriasLayout.createSequentialGroup()
                .addGroup(PTutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTutoriasLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2))
                    .addGroup(PTutoriasLayout.createSequentialGroup()
                        .addGroup(PTutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PTutoriasLayout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(jLabel20)
                                .addGap(68, 68, 68)
                                .addComponent(ListaTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(Aceptar))
                            .addGroup(PTutoriasLayout.createSequentialGroup()
                                .addGap(439, 439, 439)
                                .addComponent(FechaActual))
                            .addGroup(PTutoriasLayout.createSequentialGroup()
                                .addGap(402, 402, 402)
                                .addComponent(jLabel14)))
                        .addGap(0, 150, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PTutoriasLayout.setVerticalGroup(
            PTutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTutoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FechaActual)
                .addGap(35, 35, 35)
                .addGroup(PTutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(ListaTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aceptar))
                .addGap(53, 53, 53)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(RegistroTutoria)
                .addGap(94, 94, 94))
        );

        Menu.addTab("Tutoria", PTutorias);

        jPanel5.setBackground(new java.awt.Color(204, 153, 0));

        jLabel1.setFont(new java.awt.Font("Dubai Light", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Tutorias");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 1268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String getFecha(){
        fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        return formato.format(fecha);
    }
    
    public void cargarTutoresCita(){
        ListaTutor.removeAllItems();
        tutor_nom.clear();
        cita_horas.clear();        
        ListaTutor.addItem(SELECCIONA);
        int nc = 1;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String ff = formato.format(fecha);
        citas.sort(Comparator.comparing((Cita c) -> c.getTutor().getNombre())
            .thenComparing(Cita::getHora));
        for(Cita dCita: citas){
            if(ff.equals(formato.format(dCita.getFecha())) && dCita.getEstado().equals("0")){
                ListaTutor.addItem(dCita.getTutor().getNombre() + " - Hora: " + dCita.getHora() +":00");
                tutor_nom.put(dCita.getTutor().getNombre() + " - Hora: " + dCita.getHora() +":00",dCita.getTutor());
                cita_horas.put(nc++,dCita);
            }
        }
    }
    public void cargarTutores(){
        LTutores.removeAllItems();
        LTutores.addItem("Selecciona Tutor");
        for(Tutor dtutor: tutores) LTutores.addItem(dtutor.getNombre());
    }
    public void cargarEstudiantes(){
        mestudiantes = new DefaultListModel();
        mtutorados = new DefaultListModel();
        mestudiantes.clear();
        for(Tutorado dtutorado : tutorados) 
            if(dtutorado.getTutor() == null){
                mestudiantes.addElement(dtutorado.getNombre());
                tutorado_nom.put(dtutorado.getNombre(),dtutorado);
            }
    }
    public void configurarComboBox(){
        cbCarreras.removeAllItems();
        String[] opcionesCarrera = {"Ingeniería Electrónica", "Ingeniería Civil", /* ... todas tus carreras ... */};
        for(String carrera : opcionesCarrera) {
            cbCarreras.addItem(carrera);  
        }
    }
    
    public void configurarJSpinner(){
        //int inicio = tutor.getTutoradoCollection()
        min = cTutor.getTutorCount()+1;
        snm = new SpinnerNumberModel(min, min, max, 1);    
        dnt.setModel(snm);  
    }
    
    private void dnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dnActionPerformed

    private void ddhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddhActionPerformed

    private void cbCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCarrerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCarrerasActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Validaciones básicas (puedes añadir más)
        if (dn.getText().trim().isEmpty() || ddh.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nombre y Días/Horas son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        tutor = new Tutor(); // Crea una nueva instancia

        // NumTarjeta: Si es autoincremental en BD, no lo establezcas aquí.
        // Si no, obtén el valor del spinner.
        tutor.setNumTarjeta((Integer) dnt.getValue()); // Asumiendo que numTarjeta no es el PK autoincremental.
                                                      // Si idPersona es el PK autoincremental, numTarjeta es un campo normal.
        tutor.setNombre(dn.getText().trim());
        tutor.setCarrera((String) cbCarreras.getSelectedItem());

        // El campo 'ddh' parece combinar días y horas. Necesitas una forma consistente de almacenarlo.
        // La entidad Tutor tiene campos separados 'dias' y 'horas'.
        // Deberás decidir cómo parsear 'ddh.getText()' en esos dos campos o modificar la entidad/UI.
        // Ejemplo simple (necesitarás mejor lógica de parseo):
        String diasHorasInput = ddh.getText().trim();
        // Lógica simple para separar:
        String[] partesDH = diasHorasInput.split(";"); // Suponiendo formato "L-M-X;08-12"
        String diasTutor = "";
        String horasTutor = "";
        if (partesDH.length > 0) diasTutor = partesDH[0].trim();
        if (partesDH.length > 1) horasTutor = partesDH[1].trim();

        tutor.setDias(diasTutor);   // Asignar los días parseados
        tutor.setHoras(horasTutor); // Asignar las horas parseadas

        try {
            cTutor.create(tutor);
            tutores.add(tutor); // Añadir a la lista en memoria
            if (mtt != null) { // mtt es el modelo de la tabla ttutores
                mtt.fireTableDataChanged(); // Notificar a la tabla en la pestaña "Control"
            }
            // cargarTutores(); // Vuelve a cargar el ComboBox LTutores en la pestaña "Asignar Tutor"
            JOptionPane.showMessageDialog(this, "Tutor agregado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            // limpiarCamposAgregarTutor(); // Un método para limpiar los campos de esta pestaña
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agregar tutor: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public ImageIcon redimensionarImagen(String ruta, int ancho, int alto) {
        // 'nombreArchivoImagen' ahora sería solo "imagenes/icono.png"
        java.net.URL imgUrl = getClass().getResource("imagenes/icono.png");
        if (imgUrl == null) {
            System.err.println("No se pudo encontrar el recurso de imagen: " + "imagenes/icono.png" + " (relativo a " + getClass().getPackage().getName() + ")");
            // Opcionalmente, devuelve un icono por defecto o null y maneja el error
            return null; // O un icono por defecto
        }
        ImageIcon icono = new ImageIcon(imgUrl);
        Image imagen = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        return new ImageIcon(imagen);
    }
    
    private void moverTutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moverTutActionPerformed
        // TODO add your handling code here:
        int iest_sel[] = tutoradoss.getSelectedIndices();
        for (int x = iest_sel.length-1; x >= 0; x--){
            mestudiantes.addElement(mtutorados.get(iest_sel[x]));
            mtutorados.remove(iest_sel[x]);
        }
        moverTut.setEnabled(!mtutorados.isEmpty());
        moverEst.setEnabled(!mestudiantes.isEmpty());
    }//GEN-LAST:event_moverTutActionPerformed

    private void asignarTutoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarTutoradoActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Confirma la asignacion de tutor " + LTutores.getSelectedItem() + "?") == 0){
            for(int nts = 0; nts < mtutorados.size(); nts++){
                Tutorado t = tutorado_nom.get(mtutorados.get(nts));
                t.setTutor(tutor);
                try{
                    cTutorado.edit(t);
                } catch (Exception ex){
                    Logger.getLogger(ITutorado.class.getName()).log(Level.SEVERE,null,ex);
                }
            }
        }
        
    }//GEN-LAST:event_asignarTutoradoActionPerformed
        
    public void cargarTutoresTutoria(){
        ListaTutor.removeAllItems();
        tutor_nom.clear();
        cita_horas.clear();        
        ListaTutor.addItem(SELECCIONA);
        int nc = 1;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String ff = formato.format(fecha);
        citas.sort(Comparator.comparing((Cita c) -> c.getTutor().getNombre())
            .thenComparing(Cita::getHora));
        for(Cita dCita: citas){
            if(ff.equals(formato.format(dCita.getFecha())) && dCita.getEstado().equals("0")){
                ListaTutor.addItem(dCita.getTutor().getNombre() + " - Hora: " + dCita.getHora() +":00");
                tutor_nom.put(dCita.getTutor().getNombre() + " - Hora: " + dCita.getHora() +":00",dCita.getTutor());
                cita_horas.put(nc++,dCita);
            }
        }
    }
    private void aceptarTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarTutorActionPerformed
        // TODO add your handling code here:
        if(LTutores.getSelectedItem().equals(SELECCIONA))
        JOptionPane.showMessageDialog(this,"Selecciona un Tutor");
        else
        if(JOptionPane.showConfirmDialog(this,"Confirme Selecciona al tutor " + LTutores.getSelectedItem()+"?") == 0){
            tutor = tutores.get(LTutores.getSelectedIndex()-1);
            LTutores.setEnabled(false);
            jLabel17.setText(SELECCIONADO);
            aceptarTutor.setEnabled(false);
            if(!mestudiantes.isEmpty()) moverEst.setEnabled(true);
        }
    }//GEN-LAST:event_aceptarTutorActionPerformed

    private void bctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bctActionPerformed
        // TODO add your handling code here:
        LTutores.setEnabled(true);
        jLabel1.setText(SELECCIONA);
        aceptarTutor.setEnabled(true);
    }//GEN-LAST:event_bctActionPerformed

    private void moverEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moverEstActionPerformed
        // TODO add your handling code here:
        int iest_sel[] = estudiantes.getSelectedIndices();
        for (int x = iest_sel.length-1; x >= 0; x--){
            mtutorados.addElement(mestudiantes.get(iest_sel[x]));
            mestudiantes.remove(iest_sel[x]);
        }
        moverEst.setEnabled(!mestudiantes.isEmpty());
        moverTut.setEnabled(!mtutorados.isEmpty());
    }//GEN-LAST:event_moverEstActionPerformed

    private void ListaTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaTutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaTutorActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        if(!(ListaTutor.getSelectedItem().equals(SELECCIONA))){

            cita = cita_horas.get(ListaTutor.getSelectedIndex());

            tutorados_s = new ArrayList<>();
            for (Tutorado dt: tutorados)
            if(dt.getTutor()!= null && dt.getTutor().equals(cita.getTutor())) tutorados_s.add(dt);

            datosCitas = new ArrayList<>();
            for(Tutorado dt: tutorados_s){
                DatosTablaCitas dtc = new DatosTablaCitas(dt);
                datosCitas.add(dtc);
            }
            modTabCita = new MTablaCita(datosCitas);
            ltutorados.setModel(modTabCita);
        } else JOptionPane.showMessageDialog(this,"Seleccione un Tutor - Hola");
    }//GEN-LAST:event_AceptarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMenuTutorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMenuTutorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMenuTutorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMenuTutorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            FlatMacDarkLaf.setup();
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMenuTutorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JPanel AgregarTutor;
    private javax.swing.JPanel AsignarTutor;
    private javax.swing.JLabel FechaActual;
    private javax.swing.JLabel ImagenTutor;
    private javax.swing.JComboBox<String> LTutores;
    private javax.swing.JComboBox<String> ListaTutor;
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JPanel PCitas;
    private javax.swing.JPanel PInicio;
    private javax.swing.JPanel PTutorados;
    private javax.swing.JPanel PTutores;
    private javax.swing.JPanel PTutorias;
    private javax.swing.JButton RegistroTutoria;
    private javax.swing.JButton aceptarTutor;
    private javax.swing.JButton asignarTutorado;
    private javax.swing.JButton bct;
    private javax.swing.JComboBox<String> cbCarreras;
    private javax.swing.JTextField ddh;
    private javax.swing.JTextField dn;
    private javax.swing.JSpinner dnt;
    private javax.swing.JList<String> estudiantes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable ltutorados;
    private javax.swing.JButton moverEst;
    private javax.swing.JButton moverTut;
    private javax.swing.JTable ttutores;
    private javax.swing.JTable ttutores1;
    private javax.swing.JTable ttutores2;
    private javax.swing.JTable ttutores3;
    private javax.swing.JList<String> tutoradoss;
    // End of variables declaration//GEN-END:variables
}
