/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.ComentariosRevisionTallerJpaController;
import control.Conexion;
import control.EventosJpaController;
import control.UsuariosJpaController;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ComentariosRevisionTaller;
import modelo.Eventos;
import modelo.Usuarios;

/**
 *
 * @author Diego Garcia
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private Usuarios usuarioActual;
    
    public VentanaPrincipal(Usuarios u) {
        initComponents();
        this.usuarioActual = u;
        lblBienvenida.setText("!Bienvenido, " + u.getNombre() + "!");
        lblNombre.setText("Nombre: " + u.getNombre());
        lblCorreo.setText("Correo: " + u.getCorreo());
        lblRol.setText("Rol : " + u.getRol());
        lblNumControl.setText("Número de control: " + u.getNumeroControl());
        
        // Manipulacion del DialogGestionUusarios
        cargarUsuariosEnTabla();
        seleccionarUsuarios();
        // Manipulacion del DialogGestionEventos
        cargarEventosEnTabla();
        seleccionarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogGestionUsuarios = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        encabezado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboURol = new javax.swing.JComboBox<>();
        txtUID = new javax.swing.JTextField();
        txtUEmail = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtUNumControl = new javax.swing.JTextField();
        txtUNombre = new javax.swing.JTextField();
        passContrasena = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        encabezado1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttUsuarios = new javax.swing.JTable();
        DialogGestionEventos = new javax.swing.JDialog();
        encabezado2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ttEventos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        encabezado4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtENombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        btnECrear = new javax.swing.JButton();
        btnEModificar = new javax.swing.JButton();
        btnEEliminar = new javax.swing.JButton();
        btnELimpiar = new javax.swing.JButton();
        cboEstado = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JCalendar();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtEDescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEInicio = new javax.swing.JTextField();
        txtEFin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEID = new javax.swing.JTextField();
        lblBienvenida = new javax.swing.JLabel();
        panelEstatus = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblNumControl = new javax.swing.JLabel();
        menuBarraPrincipal = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuGestion = new javax.swing.JMenu();
        opcionUsuarios = new javax.swing.JMenuItem();
        opcionEventos = new javax.swing.JMenuItem();
        opcionTalleres = new javax.swing.JMenuItem();
        opcionConvocatorias = new javax.swing.JMenuItem();
        opcionEvidencias = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuInscripcion = new javax.swing.JMenu();
        opcionInscripcion = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        opcionAyuda = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        opcionCerrarSesion = new javax.swing.JMenuItem();
        opcionSalir = new javax.swing.JMenuItem();

        DialogGestionUsuarios.setTitle("Gestión de usuarios");

        jPanel1.setToolTipText("");

        encabezado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encabezado.setText("Datos del usuario");

        jLabel2.setText("ID:");

        jLabel4.setText("Nombre:");

        jLabel6.setText("Contraseña:");

        jLabel7.setText("Núm. de Control:");

        jLabel8.setText("Rol:");

        cboURol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOCENTE", "TALLERISTA", "ADMINISTRADOR" }));
        cboURol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboURolActionPerformed(evt);
            }
        });

        txtUID.setEditable(false);

        txtUEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUEmailActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtUNumControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUNumControlActionPerformed(evt);
            }
        });

        txtUNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUNombreActionPerformed(evt);
            }
        });

        jLabel9.setText("Email:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(encabezado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUEmail)
                        .addComponent(cboURol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUID, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtUNumControl)
                        .addComponent(txtUNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addComponent(passContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(21, 21, 21)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(encabezado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboURol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        encabezado1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encabezado1.setText("Lista de usuarios");

        ttUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Email", "Rol", "Núm. de Control"
            }
        ));
        jScrollPane1.setViewportView(ttUsuarios);

        javax.swing.GroupLayout DialogGestionUsuariosLayout = new javax.swing.GroupLayout(DialogGestionUsuarios.getContentPane());
        DialogGestionUsuarios.getContentPane().setLayout(DialogGestionUsuariosLayout);
        DialogGestionUsuariosLayout.setHorizontalGroup(
            DialogGestionUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogGestionUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogGestionUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogGestionUsuariosLayout.createSequentialGroup()
                        .addComponent(encabezado1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        DialogGestionUsuariosLayout.setVerticalGroup(
            DialogGestionUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogGestionUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encabezado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        encabezado2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encabezado2.setText("Lista de eventos");

        ttEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripción", "Fecha", "Hora de inicio", "Hora de fin", "Lugar", "Estado"
            }
        ));
        jScrollPane2.setViewportView(ttEventos);

        jPanel3.setToolTipText("");

        encabezado4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encabezado4.setText("Datos del evento");

        jLabel15.setText("Nombre:");

        jLabel16.setText("Descripción:");

        jLabel17.setText("Fecha:");

        txtENombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtENombreActionPerformed(evt);
            }
        });

        jLabel20.setText("Lugar:");

        btnECrear.setText("Crear");
        btnECrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnECrearActionPerformed(evt);
            }
        });

        btnEModificar.setText("Modificar");
        btnEModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEModificarActionPerformed(evt);
            }
        });

        btnEEliminar.setText("Eliminar");

        btnELimpiar.setText("Limpiar");
        btnELimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnELimpiarActionPerformed(evt);
            }
        });

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLANIFICADO", "CONFIRMADO", "EN_CURSO", "FINALIZADO", "CANCELADO", "POSPUESTO" }));
        cboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoActionPerformed(evt);
            }
        });

        jLabel21.setText("Estado:");

        txtEDescripcion.setColumns(20);
        txtEDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtEDescripcion);

        jLabel3.setText("Hora de fin:");

        jLabel5.setText("Hora de inicio:");

        jLabel10.setText("ID:");

        txtEID.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(btnECrear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnEModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnEEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(12, 12, 12)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLugar, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(txtEID)
                                    .addComponent(txtENombre)
                                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEInicio)
                                    .addComponent(txtEFin)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnELimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(encabezado4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(encabezado4)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtENombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addComponent(txtLugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnECrear)
                    .addComponent(btnEModificar)
                    .addComponent(btnEEliminar)
                    .addComponent(btnELimpiar))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout DialogGestionEventosLayout = new javax.swing.GroupLayout(DialogGestionEventos.getContentPane());
        DialogGestionEventos.getContentPane().setLayout(DialogGestionEventosLayout);
        DialogGestionEventosLayout.setHorizontalGroup(
            DialogGestionEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogGestionEventosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogGestionEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DialogGestionEventosLayout.createSequentialGroup()
                        .addComponent(encabezado2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                .addContainerGap())
        );
        DialogGestionEventosLayout.setVerticalGroup(
            DialogGestionEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogGestionEventosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encabezado2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AcademicPlus - Ventana Principal");

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("¡Bienvenido, !");
        lblBienvenida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estatus del usuario");

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre.setText("Nombre: ");

        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCorreo.setText("Correo: ");
        lblCorreo.setPreferredSize(new java.awt.Dimension(50, 16));

        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRol.setText("Rol: ");

        lblNumControl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumControl.setText("Número de control: ");

        javax.swing.GroupLayout panelEstatusLayout = new javax.swing.GroupLayout(panelEstatus);
        panelEstatus.setLayout(panelEstatusLayout);
        panelEstatusLayout.setHorizontalGroup(
            panelEstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstatusLayout.createSequentialGroup()
                .addGroup(panelEstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstatusLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(panelEstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelEstatusLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1)))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        panelEstatusLayout.setVerticalGroup(
            panelEstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstatusLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumControl)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        menuArchivo.setText("Archivo");
        menuBarraPrincipal.add(menuArchivo);

        menuGestion.setText("Gestión");

        opcionUsuarios.setText("Usuarios");
        opcionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionUsuariosActionPerformed(evt);
            }
        });
        menuGestion.add(opcionUsuarios);

        opcionEventos.setText("Eventos");
        opcionEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionEventosActionPerformed(evt);
            }
        });
        menuGestion.add(opcionEventos);

        opcionTalleres.setText("Talleres");
        menuGestion.add(opcionTalleres);

        opcionConvocatorias.setText("Convocatorias");
        menuGestion.add(opcionConvocatorias);

        opcionEvidencias.setText("Evidencias");
        menuGestion.add(opcionEvidencias);

        menuBarraPrincipal.add(menuGestion);

        menuReportes.setText("Reportes");
        menuBarraPrincipal.add(menuReportes);

        menuInscripcion.setText("Inscripción");

        opcionInscripcion.setText("Realizar una inscripción");
        opcionInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionInscripcionActionPerformed(evt);
            }
        });
        menuInscripcion.add(opcionInscripcion);

        menuBarraPrincipal.add(menuInscripcion);

        menuAyuda.setText("Ayuda");

        opcionAyuda.setText("Manual y documentación");
        opcionAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAyudaActionPerformed(evt);
            }
        });
        menuAyuda.add(opcionAyuda);

        menuBarraPrincipal.add(menuAyuda);

        menuSalir.setText("Salir");

        opcionCerrarSesion.setText("Cerrar sesión");
        opcionCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionCerrarSesionActionPerformed(evt);
            }
        });
        menuSalir.add(opcionCerrarSesion);

        opcionSalir.setText("Salir");
        opcionSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSalirActionPerformed(evt);
            }
        });
        menuSalir.add(opcionSalir);

        menuBarraPrincipal.add(menuSalir);

        setJMenuBar(menuBarraPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblBienvenida)
                .addGap(18, 18, 18)
                .addComponent(panelEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionInscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionInscripcionActionPerformed

    private void opcionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionUsuariosActionPerformed
        // TODO add your handling code here:
        DialogGestionUsuarios.setVisible(true);
        DialogGestionUsuarios.setSize(750,450);
        DialogGestionUsuarios.setLocationRelativeTo(this);
    }//GEN-LAST:event_opcionUsuariosActionPerformed

    private void opcionCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionCerrarSesionActionPerformed
        // TODO add your handling code here:
        VentanaLogin login = new VentanaLogin();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_opcionCerrarSesionActionPerformed

    private void opcionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_opcionSalirActionPerformed

    private void opcionAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAyudaActionPerformed
        // TODO add your handling code here:
        try {
            try {
                Desktop.getDesktop().browse(new URI("https://github.com/jangelmm/AcademicPlus.git"));
            } catch (IOException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_opcionAyudaActionPerformed

    private void cboURolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboURolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboURolActionPerformed

    private void txtUNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUNombreActionPerformed

    private void opcionEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEventosActionPerformed
        // TODO add your handling code here:
        DialogGestionEventos.setVisible(true);
        DialogGestionEventos.setSize(750, 450);
        DialogGestionEventos.setLocationRelativeTo(this);
    }//GEN-LAST:event_opcionEventosActionPerformed

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoActionPerformed

    private void txtENombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtENombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtENombreActionPerformed

    private void txtUEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUEmailActionPerformed

    private void txtUNumControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUNumControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUNumControlActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        // Crear una instancia de la entidad
        Usuarios nuevo = new Usuarios();
        nuevo.setNombre(txtUNombre.getText());
        nuevo.setCorreo(txtUEmail.getText());
        nuevo.setContrasenaHash(new String(passContrasena.getPassword()));
        nuevo.setRol(cboURol.getSelectedItem().toString());
        nuevo.setNumeroControl(txtUNumControl.getText());

        try {
            UsuariosJpaController controller = new UsuariosJpaController(Conexion.getEMF());
            controller.create(nuevo); // Método de instancia, no static
            cargarUsuariosEnTabla(); // Refresca la tabla
            limpiarCamposUsuario();  // Limpia los campos del formulario
            JOptionPane.showMessageDialog(this, "Usuario insertado exitosamente");
        } catch (Exception e) {
            System.err.println("Error al insertar el usuario: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        if (txtUID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario para modificar.");
            return;
        }

        try {
            int id = Integer.parseInt(txtUID.getText());

            // Crear controlador JPA
            UsuariosJpaController controller = new UsuariosJpaController(Conexion.getEMF());
            
            // Obtener el usuario desde la base de datos
            Usuarios usuarioExistente = controller.findUsuarios(id);

            if (usuarioExistente != null) {
                // Actualizar los valores
                usuarioExistente.setNombre(txtUNombre.getText());
                usuarioExistente.setCorreo(txtUEmail.getText());
                usuarioExistente.setRol(cboURol.getSelectedItem().toString());
                usuarioExistente.setNumeroControl(txtUNumControl.getText());

                // Guardar los cambios
                controller.edit(usuarioExistente);

                cargarUsuariosEnTabla();
                limpiarCamposUsuario();
                JOptionPane.showMessageDialog(this, "Usuario modificado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "El usuario no fue encontrado.");
            }
        } catch (Exception e) {
            System.err.println("Error al actualizar usuario: " + e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtUID.getText()); // ID del usuario a eliminar
        int idUsuarioGenerico = 1; // ID del usuario genérico (sistema)

        int confirm = JOptionPane.showConfirmDialog(this, 
            "¿Estás segura de que deseas eliminar este usuario?\nSe reasignarán sus registros al usuario genérico.", 
            "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("AcademicPlusPU");
            EntityManager em = emf.createEntityManager();

            try {
                em.getTransaction().begin();
                // Reasignar referencias en ComentarioRevisionTaller (idUsuarioComentarista)
                em.createQuery("UPDATE ComentarioRevisionTaller c SET c.usuario.idUsuario = :nuevoId WHERE c.usuario.idUsuario = :actualId")
                  .setParameter("nuevoId", idUsuarioGenerico)
                  .setParameter("actualId", id)
                  .executeUpdate();

                // Reasignar referencias en Notificaciones (idUsuarioDestinatario)
                em.createQuery("UPDATE Notificaciones n SET n.idUsuarioDestinatario.idUsuario = :nuevoId WHERE n.idUsuarioDestinatario.idUsuario = :actualId")
                  .setParameter("nuevoId", idUsuarioGenerico)
                  .setParameter("actualId", id)
                  .executeUpdate();

                // Reasignar referencias en Evidencias (idUsuarioSubio)
                em.createQuery("UPDATE Evidencias e SET e.idUsuarioSubio.idUsuario = :nuevoId WHERE e.idUsuarioSubio.idUsuario = :actualId")
                  .setParameter("nuevoId", idUsuarioGenerico)
                  .setParameter("actualId", id)
                  .executeUpdate();

                // Reasignar referencias en BitacorasEventos (idUsuarioRegistra)
                em.createQuery("UPDATE BitacorasEventos b SET b.idUsuarioRegistra.idUsuario = :nuevoId WHERE b.idUsuarioRegistra.idUsuario = :actualId")
                  .setParameter("nuevoId", idUsuarioGenerico)
                  .setParameter("actualId", id)
                  .executeUpdate();

                // Reasignar referencias en EventoParticipantesTalleres (idTallerista)
                em.createQuery("UPDATE EventoParticipantesTalleres ept SET ept.idTallerista.idUsuario = :nuevoId WHERE ept.idTallerista.idUsuario = :actualId")
                  .setParameter("nuevoId", idUsuarioGenerico)
                  .setParameter("actualId", id)
                  .executeUpdate();

                // Reasignar referencias en Convocatorias (idUsuarioPublica)
                em.createQuery("UPDATE Convocatorias c SET c.idUsuarioPublica.idUsuario = :nuevoId WHERE c.idUsuarioPublica.idUsuario = :actualId")
                  .setParameter("nuevoId", idUsuarioGenerico)
                  .setParameter("actualId", id)
                  .executeUpdate();

                // Reasignar referencias en Eventos (idDocenteResponsable)
                em.createQuery("UPDATE Eventos e SET e.idDocenteResponsable.idUsuario = :nuevoId WHERE e.idDocenteResponsable.idUsuario = :actualId")
                  .setParameter("nuevoId", idUsuarioGenerico)
                  .setParameter("actualId", id)
                  .executeUpdate();

                // Reasignar referencias en Talleres (idUsuarioProponente)
                em.createQuery("UPDATE Talleres t SET t.idUsuarioProponente.idUsuario = :nuevoId WHERE t.idUsuarioProponente.idUsuario = :actualId")
                  .setParameter("nuevoId", idUsuarioGenerico)
                  .setParameter("actualId", id)
                  .executeUpdate();
/*
                // Reasignar relaciones (ejemplo con comentario_revision, notificacion, etc.)
                em.createQuery("UPDATE ComentarioRevisionTaller c SET c.usuario.idUsuario = :nuevoId WHERE c.usuario.idUsuario = :actualId")
                  .setParameter("nuevoId", idUsuarioGenerico)
                  .setParameter("actualId", id)
                  .executeUpdate();

                em.createQuery("UPDATE Notificaciones n SET n.usuario.idUsuario = :nuevoId WHERE n.usuario.idUsuario = :actualId")
                  .setParameter("nuevoId", idUsuarioGenerico)
                  .setParameter("actualId", id)
                  .executeUpdate();

                em.createQuery("UPDATE Evidencias e SET e.usuario.idUsuario = :nuevoId WHERE e.usuario.idUsuario = :actualId")
                  .setParameter("nuevoId", idUsuarioGenerico)
                  .setParameter("actualId", id)
                  .executeUpdate();

                em.createQuery("UPDATE Bitacora b SET b.usuario.idUsuario = :nuevoId WHERE b.usuario.idUsuario = :actualId")
                  .setParameter("nuevoId", idUsuarioGenerico)
                  .setParameter("actualId", id)
                  .executeUpdate();
*/
                // Buscar y eliminar el usuario
                Usuarios usuarioAEliminar = em.find(Usuarios.class, id);
                if (usuarioAEliminar != null) {
                    em.remove(usuarioAEliminar);
                }

                em.getTransaction().commit();

                cargarUsuariosEnTabla(); // Refresca la tabla
                limpiarCamposUsuario(); // Limpia los campos
                JOptionPane.showMessageDialog(this, "Usuario eliminado y registros reasignados.");
            } catch (Exception e) {
                if (em.getTransaction().isActive()) em.getTransaction().rollback();
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al eliminar usuario: " + e.getMessage());
            } finally {
                em.close();
                emf.close();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCamposUsuario();
    }//GEN-LAST:event_btnLimpiarActionPerformed
    private void limpiarCamposUsuario() {
        txtUID.setText("");
        txtUNombre.setText("");
        txtUEmail.setText("");
        cboURol.setSelectedIndex(0);
        txtUNumControl.setText("");
    }
    
    private void btnELimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnELimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCamposEventos();
    }//GEN-LAST:event_btnELimpiarActionPerformed
    private void limpiarCamposEventos() {
        txtEID.setText("");
        txtENombre.setText("");
        txtEDescripcion.setText("");
        txtLugar.setText("");
        cboEstado.setSelectedIndex(0);
        calendario.setDate(new java.util.Date()); // Establece la fecha actual
        txtEInicio.setText("");
        txtEFin.setText("");
    }
    
    private void btnECrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnECrearActionPerformed
        // TODO add your handling code here:
        // Crear una instancia de la entidad
        Eventos nuevo = new Eventos();
        nuevo.setNombre(txtENombre.getText());
        nuevo.setDescripcionPublica(txtEDescripcion.getText());
        nuevo.setLugarEvento(txtLugar.getText());
        nuevo.setEstadoEvento(cboEstado.getSelectedItem().toString());
        nuevo.setFechaEvento(calendario.getDate());

        // Convertir las horas de tipo String (HH:mm) a Time
        try {
            // Obtener las horas como String desde los JTextField
            String horaInicioStr = txtEInicio.getText();  // Formato: "HH:mm" (ejemplo "10:00")
            String horaFinStr = txtEFin.getText();        // Formato: "HH:mm" (ejemplo "12:00")

            // Añadir ":00" para hacer que el formato sea "HH:mm:ss" (ejemplo "10:00:00")
            //horaInicioStr += ":00";
            //horaFinStr += ":00";

            // Convertir el String a Time
            Time horaInicio = Time.valueOf(horaInicioStr);  // Convierte a Time
            Time horaFin = Time.valueOf(horaFinStr);        // Convierte a Time

            // Asignar las horas al objeto evento
            nuevo.setHoraInicioEvento(horaInicio);
            nuevo.setHoraFinEvento(horaFin);

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Error al formatear la hora. Asegúrese de que la hora esté en formato HH:mm.");
            return; // Si hay un error, salir del método
        }
        
        try {
            EventosJpaController controller = new EventosJpaController(Conexion.getEMF());
            controller.create(nuevo); // Método de instancia, no static
            cargarEventosEnTabla(); // Refresca la tabla
            limpiarCamposEventos();  // Limpia los campos del formulario
            JOptionPane.showMessageDialog(this, "Evento insertado exitosamente");
        } catch (Exception e) {
            System.err.println("Error al insertar el evento: " + e.getMessage());
        }
    }//GEN-LAST:event_btnECrearActionPerformed

    private void btnEModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEModificarActionPerformed
        // TODO add your handling code here:
        // Verificar si se ha seleccionado un evento
        if (txtEID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un evento para modificar.");
            return;
        }

        try {
            // Obtener el ID del evento desde el campo de texto
            int id = Integer.parseInt(txtEID.getText());

            // Crear el controlador JPA para eventos
            EventosJpaController controller = new EventosJpaController(Conexion.getEMF());

            // Obtener el evento desde la base de datos
            Eventos eventoExistente = controller.findEventos(id);

            if (eventoExistente != null) {
                // Actualizar los valores con los nuevos datos ingresados en el formulario
                eventoExistente.setNombre(txtENombre.getText());
                eventoExistente.setDescripcionPublica(txtEDescripcion.getText());
                eventoExistente.setLugarEvento(txtLugar.getText());
                eventoExistente.setEstadoEvento(cboEstado.getSelectedItem().toString());

                // Obtener la fecha del JCalendar y actualizar
                eventoExistente.setFechaEvento(calendario.getDate());

                // Convertir las horas de tipo String (HH:mm) a Time
                try {
                    String horaInicioStr = txtEInicio.getText(); // Formato: "HH:mm"
                    String horaFinStr = txtEFin.getText();       // Formato: "HH:mm"

                    // Añadir ":00" para convertir a "HH:mm:ss"
                    horaInicioStr += ":00";
                    horaFinStr += ":00";

                    // Convertir a tipo Time
                    Time horaInicio = Time.valueOf(horaInicioStr);
                    Time horaFin = Time.valueOf(horaFinStr);

                    // Actualizar las horas del evento
                    eventoExistente.setHoraInicioEvento(horaInicio);
                    eventoExistente.setHoraFinEvento(horaFin);

                } catch (IllegalArgumentException e) {
                    JOptionPane.showMessageDialog(this, "Error al formatear las horas. Asegúrese de que las horas estén en formato HH:mm.");
                    return; // Si hay error en el formato de horas, salir del método
                }
                controller.edit(eventoExistente);
                cargarEventosEnTabla();
                limpiarCamposEventos();
                // Mensaje de éxito
                JOptionPane.showMessageDialog(this, "Evento modificado exitosamente");
            } else {
                // Si no se encuentra el evento en la base de datos
                JOptionPane.showMessageDialog(this, "El evento no fue encontrado.");
            }
        } catch (Exception e) {
            System.err.println("Error al actualizar evento: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEModificarActionPerformed
    
    // -------------------------------------------------------------------------
    // Manipulacion de DialogGestionUsuarios
    private void cargarUsuariosEnTabla() {
        DefaultTableModel modelo = (DefaultTableModel) ttUsuarios.getModel();
        modelo.setRowCount(0); // Limpiar la tabla

        try {
            UsuariosJpaController controller = new UsuariosJpaController(Conexion.getEMF());
            List<Usuarios> listaUsuarios = controller.findUsuariosEntities();

            for (Usuarios u : listaUsuarios) {
                Object[] fila = new Object[]{
                    u.getIdUsuario(),
                    u.getNombre(),
                    u.getCorreo(),
                    u.getRol(),
                    u.getNumeroControl()
                };
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            System.err.println("Error al cargar los usuarios: " + e.getMessage());
        }
    }
    private void seleccionarUsuarios() {    // Muestra en elementos filas de la tabla
        ttUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarCamposUsuario();
                int selectedRow = ttUsuarios.getSelectedRow();
                if (selectedRow != -1) {
                    DefaultTableModel model = (DefaultTableModel) ttUsuarios.getModel();
                    
                    txtUID.setText(String.valueOf((int) model.getValueAt(selectedRow, 0)));
                    txtUNombre.setText(model.getValueAt(selectedRow, 1).toString());
                    txtUEmail.setText(model.getValueAt(selectedRow, 2).toString());
                    cboURol.setSelectedItem(model.getValueAt(selectedRow, 3).toString());
                    txtUNumControl.setText(model.getValueAt(selectedRow, 4).toString());
                }
            }
        });
    }
    
    // -------------------------------------------------------------------------
    // Manipulacion de DialogGestionEventos
    private void cargarEventosEnTabla() {
        DefaultTableModel modelo2 = (DefaultTableModel) ttEventos.getModel();
        modelo2.setRowCount(0); // Limpiar la tabla

        try {
            EventosJpaController controller = new EventosJpaController(Conexion.getEMF());
            List<Eventos> listaEventos = controller.findEventosEntities();

            // Formato para la fecha
            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            // Formato para la hora
            SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm");

            for (Eventos e : listaEventos) {
                // Formatear la fecha y las horas
                String fechaFormateada = formatoFecha.format(e.getFechaEvento());
                String horaInicioFormateada = formatoHora.format(e.getHoraInicioEvento());
                String horaFinFormateada = formatoHora.format(e.getHoraFinEvento());

                // Crear la fila con los datos formateados
                Object[] fila = new Object[]{
                    e.getIdEvento(),
                    e.getNombre(),
                    e.getDescripcionPublica(),
                    fechaFormateada, // Fecha formateada
                    horaInicioFormateada, // Hora de inicio formateada
                    horaFinFormateada, // Hora de fin formateada
                    e.getLugarEvento(),
                    e.getEstadoEvento()
                };

                // Añadir la fila al modelo de la tabla
                modelo2.addRow(fila);
            }
        } catch (Exception e) {
            System.err.println("Error al cargar los eventos: " + e.getMessage());
        }
    }
    private void seleccionarEventos() {    // Muestra en elementos filas de la tabla
        ttEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarCamposEventos();
                int selectedRow = ttEventos.getSelectedRow();
                if (selectedRow != -1) {
                    DefaultTableModel model = (DefaultTableModel) ttEventos.getModel();
                    
                    txtEID.setText(String.valueOf(model.getValueAt(selectedRow, 0)));
                    txtENombre.setText(model.getValueAt(selectedRow, 1).toString());
                    txtEDescripcion.setText(model.getValueAt(selectedRow, 2).toString());
                    // **Fecha**: Convertir la fecha en el formato 'yyyy-MM-dd'
                    String fechaStr = model.getValueAt(selectedRow, 3).toString(); // Columna 3 = fecha
                    // **Fecha en JCalendar**: Convertir la fecha al tipo java.util.Date
                    try {
                        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                        java.util.Date fecha = formatoFecha.parse(fechaStr); // Convertir fecha en String a Date
                        calendario.setDate(fecha); // Establecer fecha en el JCalendar
                    } catch (Exception ex) {
                        System.err.println("Error al convertir la fecha: " + ex.getMessage());
                    }
                    
                    // **Hora Inicio**: Convertir hora en formato 'HH:mm:ss'
                    String horaInicioStr = model.getValueAt(selectedRow, 4).toString(); // Columna 4 = hora inicio
                    if (horaInicioStr != null && !horaInicioStr.isEmpty()) {
                        txtEInicio.setText(horaInicioStr); // Mostrar en el campo txtEInicio
                    }
                    // **Hora Fin**: Convertir hora en formato 'HH:mm:ss'
                    String horaFinStr = model.getValueAt(selectedRow, 5).toString(); // Columna 5 = hora fin
                    if (horaFinStr != null && !horaFinStr.isEmpty()) {
                        txtEFin.setText(horaFinStr); // Mostrar en el campo txtEFin
                    }
                    txtLugar.setText(model.getValueAt(selectedRow, 6).toString());
                    cboEstado.setSelectedItem(model.getValueAt(selectedRow, 7).toString());                    
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogGestionEventos;
    private javax.swing.JDialog DialogGestionUsuarios;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnECrear;
    private javax.swing.JButton btnEEliminar;
    private javax.swing.JButton btnELimpiar;
    private javax.swing.JButton btnEModificar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private com.toedter.calendar.JCalendar calendario;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboURol;
    private javax.swing.JLabel encabezado;
    private javax.swing.JLabel encabezado1;
    private javax.swing.JLabel encabezado2;
    private javax.swing.JLabel encabezado4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumControl;
    private javax.swing.JLabel lblRol;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBarraPrincipal;
    private javax.swing.JMenu menuGestion;
    private javax.swing.JMenu menuInscripcion;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem opcionAyuda;
    private javax.swing.JMenuItem opcionCerrarSesion;
    private javax.swing.JMenuItem opcionConvocatorias;
    private javax.swing.JMenuItem opcionEventos;
    private javax.swing.JMenuItem opcionEvidencias;
    private javax.swing.JMenuItem opcionInscripcion;
    private javax.swing.JMenuItem opcionSalir;
    private javax.swing.JMenuItem opcionTalleres;
    private javax.swing.JMenuItem opcionUsuarios;
    private javax.swing.JPanel panelEstatus;
    private javax.swing.JPasswordField passContrasena;
    private javax.swing.JTable ttEventos;
    private javax.swing.JTable ttUsuarios;
    private javax.swing.JTextArea txtEDescripcion;
    private javax.swing.JTextField txtEFin;
    private javax.swing.JTextField txtEID;
    private javax.swing.JTextField txtEInicio;
    private javax.swing.JTextField txtENombre;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtUEmail;
    private javax.swing.JTextField txtUID;
    private javax.swing.JTextField txtUNombre;
    private javax.swing.JTextField txtUNumControl;
    // End of variables declaration//GEN-END:variables
}
